[servers.SSH]

bind = "192.168.54.122:2222"
protocol = "tcp"
balance = "roundrobin"

  [servers.SSH.discovery]
  kind = "static"
  static_list = [
      "192.168.54.125 weight=1"
  ]

[servers.RDP]

bind = "192.168.54.122:3389"
protocol = "tcp"
balance = "leastconn"

  [servers.RDP.discovery]
  kind = "static"
  static_list = [
      "192.168.54.127:3389"
  ]

[servers.HTTPS]

bind = "192.168.54.122:443"
protocol = "tcp"
balance = "roundrobin"

  [servers.HTTPS.discovery]
  kind = "static"
  static_list = [
      "192.168.54.125:443 weight=1"
  ]